jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /reservaCanchasFutbolService
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mariadb://localhost:3306/reservascancha
      username: root
      password: rootCeiba
      hikari:
         poolName: pool

